version: "3.9"
services:
  ct-app2:
    container_name: ct-app2
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postg
    volumes:
      - .:/app
    depends_on:
      - postg
  postg:
    container_name: postg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=prueba
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: