version: "3.8"

services:
  # Database engine service
  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d # Monta el script de inicialización
      - ./postgres_data:/var/lib/postgresql/data

  # Database admin service
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - postgres_db

  # Billing App Backend service
  billingapp-back:
    container_name: billingApp-back
    build:
      context: ./java
      args:
        - JAR_FILE=*.jar
        - DB_PASSWORD=qwerty
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - postgres_db
    ports:
      - 8080:8080

  # Billing App Frontend service
  billingapp-front:
    container_name: billingApp-front
    build:
      context: ./angular
    depends_on:
      - billingapp-back
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 250M
        reservations:
          cpus: "0.1"
          memory: 128M
